[project]
name = "repl-nix-puppeteerscriptexecutor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit>=1.39.0",
    "watchdog>=2.5.0",
]
